export declare const isString: (s: any) => boolean;
export declare const strLen: (s: any) => any;
export declare const isEmail: (s: any) => boolean;
export declare const isPhone: (s: any) => boolean;
export declare const isNull: (s: any) => boolean;
export declare const isCurrency: (s: any) => boolean;
export declare const now: () => any;
export declare const dateFormat: (m: any, format: any) => any;
export declare const year: (m: any) => any;
export declare const date: (m: any) => any;
export declare const string: (s: any) => any;
export declare const int: (s: any) => number;
declare const defaultCustomFunctions: {
    isString: (s: any) => boolean;
    strLen: (s: any) => any;
    isEmail: (s: any) => boolean;
    isPhone: (s: any) => boolean;
    isNull: (s: any) => boolean;
    isCurrency: (s: any) => boolean;
    now: () => any;
    dateFormat: (m: any, format: any) => any;
    year: (m: any) => any;
    date: (m: any) => any;
    string: (s: any) => any;
    int: (s: any) => number;
};
export default defaultCustomFunctions;
